In [1]:
import numpy as np

In [50]:
m = np.array([[9,6,7], [4,16,12]])

In [51]:
m

array([[ 9,  6,  7],
       [ 4, 16, 12]])

In [13]:
def col(i):
    return m[:,i]

def row(i):
    return m[i,:]

In [14]:
row(1)

array([ 4,  0, -1,  3])

In [16]:
def convex(r1, r2, p):
    return r1 * p + r2 * (1-p)

In [55]:
convex(col(0), col(2), 1/2)

array([8., 8.])

In [18]:
row(0)

array([1, 5, 4, 0])

In [49]:
(9/2, 7/2)

(4.5, 3.5)

In [60]:
x = np.array([[4/5, 1/5]])

In [67]:
y = np.array([[2/3 - 1/8, 1/3 - 2*1/8, 3*1/8]])

In [68]:
y.sum()

1.0

In [69]:
m

array([[ 9,  6,  7],
       [ 4, 16, 12]])

In [70]:
np.dot(np.dot(x, m), y.T)

array([[8.]])

In [71]:
np.dot(x, m)

array([[8., 8., 8.]])

In [72]:
x

array([[0.8, 0.2]])

In [185]:
A = np.array([[2,1,4,3], [3,6,6,2], [2,8,4,1], [3,0,3,5]])
B = np.array([[1, 1, 4, 3], [3, 2, 6, 2], [2, 8, 3, 1], [3,0,3,1]])

In [186]:
A + B

array([[ 3,  2,  8,  6],
       [ 6,  8, 12,  4],
       [ 4, 16,  7,  2],
       [ 6,  0,  6,  6]])

In [187]:
def ess(z, A, x):
    ans = np.dot(np.dot(z, A), x.T)
    print(ans)
    return ans


def check(z, A, x):
    

IndentationError: expected an indented block (<ipython-input-187-f55efd4b2430>, line 8)

In [188]:
A

array([[2, 1, 4, 3],
       [3, 6, 6, 2],
       [2, 8, 4, 1],
       [3, 0, 3, 5]])

In [189]:
z1 = np.array([[1,0,0]])
z2 = np.array([[0,1,0]])
z3 = np.array([[0,0,1]])
z = [z1, z2, z3]

In [190]:
x = np.array([[1/2, 1/2, 0]])

In [191]:
[ess(zi, A, x) < ess(x, A, x) for zi in z]

ValueError: shapes (1,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

In [192]:
p = np.array([[1/10, 2/5, 2/5, 1/10]])

In [193]:
ess(p, A, x) < ess(x, A, x)

ValueError: shapes (1,4) and (3,1) not aligned: 4 (dim 1) != 3 (dim 0)

In [194]:
ess(p, A, p) < ess(x, A, p)

[[4.61]]


ValueError: shapes (1,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

In [195]:
ess(p, A, p)

[[4.61]]


array([[4.61]])

In [196]:
ess(p, B, p)

[[3.76]]


array([[3.76]])

In [197]:
p

array([[0.1, 0.4, 0.4, 0.1]])

In [198]:
A

array([[2, 1, 4, 3],
       [3, 6, 6, 2],
       [2, 8, 4, 1],
       [3, 0, 3, 5]])

In [199]:
np.dot(p, A)

array([[2.5, 5.7, 4.7, 2. ]])

In [201]:
p.sum()

1.0